In [2]:
import numpy as np
def sigm(x):
    return 1 / (1 + np.exp(-x))
def sigm_d(sig):
    return sig * (1 - sig)
input = 2
hidden = 3
output = 3
inputs = np.random.uniform(0.01, 1.0,input)
targets = np.random.uniform(0.1, 1.0,output)
eta = np.random.uniform(0.01, 1.0)
w = np.random.uniform(0.1, 1.0,(hidden,input))
theta = np.random.uniform(0.1, 1.0,(output,hidden))

i=0
l=float('inf')
while l>1e-16:
    h = np.dot(w,inputs)
    Oh = sigm(h)
    o = np.dot(theta,Oh)
    Oj = sigm(o)

    l = 0.5*np.sum((targets - Oj)**2)
    err_out = (Oj - targets)*sigm_d(Oj)
    del_theta = np.outer(err_out,Oh)
    err_hidden = np.dot(theta.T, err_out)*sigm_d(Oh)
    del_w = np.outer(err_hidden,inputs)

    theta = theta - eta*del_theta
    w = w - eta*del_w

    print(f"i {i}")
    print("Inputs:",inputs)
    print("Targets:",targets)
    print("Hidden Outputs (Oh):",Oh)
    print("Outputs (Oj):",Oj)
    print("Loss:",l)
    print("New w:",w)
    print("New theta:",theta)
    print("\n")
    i+=1
print("Total Iterations:",i)
print("Total Loss:",l)

i 0
Inputs: [0.96630369 0.83032863]
Targets: [0.54616366 0.67216198 0.36838747]
Hidden Outputs (Oh): [0.75403611 0.79770079 0.75746301]
Outputs (Oj): [0.85675309 0.82058418 0.79400586]
Loss: 0.1498229795876672
New w: [[0.45348999 0.81497764]
 [0.89762792 0.60263516]
 [0.46050767 0.83128334]]
New theta: [[0.71130731 0.77161818 0.82437337]
 [0.48619351 0.85881913 0.60938282]
 [0.85379016 0.57178824 0.29957811]]


i 1
Inputs: [0.96630369 0.83032863]
Targets: [0.54616366 0.67216198 0.36838747]
Hidden Outputs (Oh): [0.75304304 0.79701904 0.75680253]
Outputs (Oj): [0.85501978 0.81932816 0.79007679]
Loss: 0.14743593169229643
New w: [[0.45031631 0.81225055]
 [0.89513019 0.6004889 ]
 [0.45838909 0.82946288]]
New theta: [[0.70608704 0.76609305 0.81912703]
 [0.48322316 0.85567531 0.60639764]
 [0.84425398 0.56169517 0.28999432]]


i 2
Inputs: [0.96630369 0.83032863]
Targets: [0.54616366 0.67216198 0.36838747]
Hidden Outputs (Oh): [0.75205028 0.79633942 0.75614693]
Outputs (Oj): [0.85326769 0.81807